

POST http://127.0.0.1:8080/users/
content-type: application/json

{
	"name": "pedro",
	"username": "pedrogarr",
	"password": "1234"
}

###

POST http://127.0.0.1:8080/tasks/ 
content-type: application/json

{
	"description": "Yarr mate, we shall pluder the seas for riches",
	"title": "Plunder the seas 2",
	"priority": "HIGH",
	"startAt": "2023-10-06T12:30:00",
	"endAt": "2023-10-14T15:35:00",
	"idUser": "42f1216e-d47f-4ac9-a0a1-64f34584bdff"
	
}
