

POST http://127.0.0.1:8080/users/
content-type: application/json

{
	"name": "teste",
	"username": "usertest2",
	"password": "1234"
}

###

POST http://127.0.0.1:8080/tasks/ 
content-type: application/json
Authorization: Basic usertest 1234

{
	"description": "Yarr mate, we shall pluder the seas for riches",
	"title": "Plunder the seas 2",
	"priority": "HIGH",
	"startAt": "2023-10-16T12:30:00",
	"endAt": "2023-10-17T15:35:00"
	
}
###

GET  http://127.0.0.1:8080/tasks/ 
content-type: application/json
Authorization: Basic usertest 1234 
###

PUT http://127.0.0.1:8080/tasks/b558986d-74a1-473d-9c97-bee2a7cd66a4 
content-type: application/json
Authorization: Basic usertest2 1234

{
	
	"title": "and a bottle of s"

}

